### ISSUE TITLE
cpupower-openrc is missing

### ISSUE THREAD

**Issue by h4tr3d** [artix-linux/galaxy#23]
cpupower-openrc is present in Manjaro but missing in Artix.

**Comment by DamnWidget** [comment]
We don't package cpupower (linux-tools) yet that is why cpupower-openrc is missing. AFAIK when our automated building platform is stable we will be in much better position to package a larger number of packages.

**Comment by h4tr3d** [comment]
@DamnWidget, I understand. You can close issue if want (and other similar)

**Comment by thefallenrat** [comment]
`cpupower-openrc` is available now as well
