### ISSUE TITLE
Missing bbswitch for linux-ck kernel

### ISSUE THREAD

**Issue by DamnWidget** [artix-linux/galaxy#26]
Would be nice to have a version of this package that works with the linux-ck kernel (or with any 4.12 kernel).

In the meanwhile people using our linux-ck kernel should rely in `bswitch-dkms`

**Comment by graysky2** [comment]
@DamnWidget - Sorry, but I am not maintaining an AUR package for this module (don't have the time or hardware).

**Comment by DamnWidget** [comment]
Ok, don't close it, I will take care of it

**Comment by DamnWidget** [comment]
Added on 9a4c65411adef806df6293f497f5009e20537daf
