### ISSUE TITLE
Please provide pdnsd service

### ISSUE THREAD

**Issue by somenxavier** [artix-linux/galaxy#32]
Can you please provide a pdnsd-openrc package?

**Comment by archnous** [comment]
It's fairly easy to adapt the [original Gentoo openrc initscript](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-dns/pdns/files/pdns-r1) for Artix. Could you do it and create a pull request?

**Comment by udeved** [comment]
There is no pdnsd in repos, neither in arch nor artix.

**Comment by thefallenrat** [comment]
I thought there is one ? Should I import its PKGBUILD from arch?

https://www.archlinux.org/packages/community/x86_64/pdnsd/

**Comment by udeved** [comment]
we need to add the community build to our galaxy without systemd service provided.

**Comment by thefallenrat** [comment]
> we need to add the community build to our galaxy without systemd service provided.

Do you think this is good enough? https://github.com/artix-linux/galaxy/commit/18e1c32b9259989d830f2b054b637fdad11bca97

**Comment by thefallenrat** [comment]
Added and built with https://github.com/artix-linux/galaxy/commit/6495b429baf1543b5c360af7062549349d58d951 , And the package are now available in `[galaxy-testing]`

**Comment by somenxavier** [comment]
Thanks for your speed.
