### ISSUE TITLE
Change in dnscrypt-proxy init scripts

### ISSUE THREAD

**Issue by physkets** [artix-linux/galaxy#33]
According to the following commit, gentoo are moving to using the native config file of the **dnscrypt-proxy** package (/etc/dnscrypt-proxy.conf) instead of requiring configuration to be done in the conf.d and init.d files.

https://gitweb.gentoo.org/repo/gentoo.git/commit/net-dns/dnscrypt-proxy?id=0ee515fb8a5ff324983ec37c38ec1e2dc8d7aaa6

p.s. I wish the Arch maintainer of the package would update to version 1.9.5

**Comment by thefallenrat** [comment]
The package itself has already marked out-of-date, I'm sure the maintainer will update it soon

https://www.archlinux.org/packages/community/x86_64/dnscrypt-proxy/

**Comment by physkets** [comment]
Yes, but that is independent of using the new init.d & conf.d scripts.

**Comment by thefallenrat** [comment]
> Yes, but that is independent of using the new init.d & conf.d scripts.
Fine. I'll update it

**Comment by thefallenrat** [comment]
Done! https://github.com/artix-linux/galaxy/commit/c7bd55cb9b0be8fe5ba7d263dda19d4c7eb1ed78
